---
repo_base: git://git.openstack.org/openstack

version_release: kilo
version_branch: "stable/{{ version_release }}"

clone_path_prefix: "z/gl"
virtualenv_prefix: "y/virtualenvs/osvenv"

ceilometer_database: "{{ version_release}}_ceilometer"
glance_database: "{{ version_release }}_glance"
heat_database: "{{ version_release }}_heat"
keystone_database: "{{ version_release }}_keystone"
neutron_database: "{{ version_release }}_neutron"
nova_database: "{{ version_release }}_nova"

compute_driver: libvirt.LibvirtDriver
linuxnet_interface_driver: LinuxBridgeInterfaceDriver

firewall_driver: IptablesFirewallDriver
l3_interface_driver: BridgeInterfaceDriver
ml2_mechanism_driver: linuxbridge
tenant_network_types: "vlan,vxlan"
type_drivers: "local,flat,vlan,vxlan"

openstackclient_version: 1.0.4

controller_host: controller

region: RegionOne

db_user: osdb
db_password: toor
db_host: controller

admin_token: nekot
admin_password: nimda

rabbitmq_user: osrabbit
rabbitmq_password: hare
