---
version_release: kilo
version_branch: "stable/{{ version_release }}"
nova_database: "{{ version_release }}_nova"
keystone_database: "{{ version_release }}_keystone"
neutron_database: "{{ version_release }}_neutron"
clone_path_prefix: "z/gl"
l3_interface_driver: BridgeInterfaceDriver
ml2_mechanism_driver: linuxbridge
openstackclient_version: 1.0.4
firewall_driver: IptablesFirewallDriver
tenant_network_types: "vlan,vxlan"
type_drivers: "local,flat,vlan,vxlan"
