---
repo_base: git://git.openstack.org/openstack

version_release: kilo
version_branch: "stable/{{version_release}}"

clone_path_prefix: "z/gl"
virtualenv_prefix: "y/virtualenvs/osvenv/{{version_release}}"

ceilometer_database: "{{ version_release}}_ceilometer"
glance_database: "{{ version_release }}_glance"
heat_database: "{{ version_release }}_heat"
keystone_database: "{{ version_release }}_keystone"
neutron_database: "{{ version_release }}_neutron"
nova_database: "{{ version_release }}_nova"

compute_driver: libvirt.LibvirtDriver
linuxnet_interface_driver: LinuxBridgeInterfaceDriver

firewall_driver: IptablesFirewallDriver
l3_interface_driver: BridgeInterfaceDriver
ml2_mechanism_driver: linuxbridge
tenant_network_types: "vlan,vxlan"
type_drivers: "local,flat,vlan,vxlan"

# Python package versions
mysql_python_version: 1.2.5
openstackclient_version: 1.0.4
libvirt_version: 1.2.12
python_memcached_version: 1.48

deprecated_keystoneclient: "{{virtualenv_bin}}/keystone"

controller_host: controller

region: RegionOne

db_user: osdb
db_password: toor
db_host: controller

# Identity service credentials
admin_token: nekot
admin_password: nimda

rabbitmq_user: osrabbit
rabbitmq_password: hare
