---
repo_base: git://git.openstack.org/openstack

version_release: mitaka
version_branch: "stable/{{version_release}}"

clone_path_prefix: "z/gl"
virtualenv_prefix: "v/{{version_release}}"

ceilometer_database: "{{ version_release}}_ceilometer"
cinder_database: "{{ version_release}}_cinder"
glance_database: "{{ version_release }}_glance"
heat_database: "{{ version_release }}_heat"
keystone_database: "{{ version_release }}_keystone"
neutron_database: "{{ version_release }}_neutron"
nova_database: "{{ version_release }}_nova"
nova_api_database: "{{ version_release }}_nova_api"

# Nova configuration
compute_driver: libvirt.LibvirtDriver

# Neutron configuration
ml2_mechanism_driver: linuxbridge
type_drivers: "flat,vlan"
physical_network_interface: em1
l3_interface_driver: BridgeInterfaceDriver

# Python package versions
libvirt_version: 1.3.1

common_pip_packages:
  pymysql:
    0.7.4
  python-memcached:
    1.58

controller_host: controller
controller_ip: 192.168.88.125

region: RegionOne

db_user: osdb
db_password: toor
db_host: controller

# Identity service credentials
admin_token: nekot
admin_password: nimda

rabbitmq_user: osrabbit
rabbitmq_password: hare
