---
- hosts: all
  vars:
    db_user: root
    db_password: naber
    keystone_repo_dir: /home/femnad/z/gl/openstack/keystone
    os_token: naber
  pre_tasks:
    - name: Install requirements with apt
      apt: name={{item}} state=latest
      become: yes
      with_items:
        - mariadb-server
        - crudini
        - memcached
        - python-memcache
        - python-dev
        - python-setuptools
        - rabbitmq-server
      when: ansible_os_family == "Debian"
      tags: packages
  tasks:
    - name: Add database admin
      script: add-db-admin.sh
      tags: db-admin-init
    - script: set-hosts.sh controller
      become: yes
      tags: host-init
    - git: repo=git://git.openstack.org/openstack/keystone dest={{keystone_repo_dir}} version=stable/kilo accept_hostkey=yes
      tags: install
    - script: install-keystone.sh {{keystone_repo_dir}}
      become: yes
      tags: install
    - name: Add keystone database
      mysql_db: name=keystone state=present login_user={{db_user}} login_password={{db_password}}
      tags: db-init
    - name: Add keystone database user
      mysql_user: name=keystone password=keystone priv=*.*:ALL state=present login_user={{db_user}} login_password={{db_password}}
      tags: db-init
    - name: Generate configuration
      script: bootstrap-keystone.sh {{keystone_repo_dir}}
      become: yes
      tags: genconfig
    - name: Configure keystone
      script: configure-keystone.sh {{os_token}}
      become: yes
      tags: config
    - name: Sync keystone database
      command: keystone-manage db_sync
      become: yes
      tags: sync-db
    - name: Add keystone services
      script: add-keystone-services.sh {{os_token}}
      tags: service
