---
- hosts: all
  vars_files:
    - environment.yaml
    - paths.yaml
  roles:
    - { role: clone, project: cinder, tags: clone }
    - { role: install, project: cinder, tags: install }
    - { role: config, project: cinder, config_files: [cinder], tags: config }
    - { role: mysql, project: cinder, sync_command: "db sync", tags: database }
    - { role: service, project: cinder, port: 8776, endpoint: "/v2/%\\(tenant_id\\)s",
        type: volume, description: "OpenStack Block Storage", tags: service }
