---
- hosts: all
  vars_files:
    - environment.yaml
    - paths.yaml
  roles:
    - { role: package,  project: nova,
        packages: [libffi-dev, libmysqlclient-dev, libpq-dev, libvirt-bin, libvirt-dev, libxml2-dev,
                 libxslt1-dev, nbd-client, pkg-config, python-dev, python-mysqldb, qemu-kvm] }
    - { role: repo-clone-install, project: nova }
    - { role: config, project: nova, config_files: [nova] }
    - { role: mysql, project: "{{project}}" }
    - { role: deprecated-service, project: nova, port: 8774, endpoint: "/v2/%(tenant_id)s",
        type: compute }
