---
- hosts: all
  vars:
    - repo_dir: /home/femnad/z/gl/openstack/nova
    - openrc_file_location: /home/femnad/y/admin-openrc.sh
    - db_user: root
    - db_password: naber
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - mongodb-server
        - mongodb-clients
      when: ansible_os_family == "Debian"
  tasks:
    - git: repo=git://git.openstack.org/openstack/ceilometer dest={{repo_dir}} version=stable/kilo accept_hostkey=yes
      tags: clone
    - name: Install ceilometer
      script: install-ceilometer.sh {{repo_dir}}
      become: yes
      tags: install
    - mysql_db: name=ceilometer state=present login_user={{db_user}} login_password={{db_password}}
      tags: db-init
    - mysql_user: name=ceilometer password=ceilometer priv=*.*:ALL state=present login_user={{db_user}} login_password={{db_password}}
      tags: db-init
    - name: Initialize MongoDB
      script: init-ceilometer-db.sh
      tags: db-init
    - name: Add services
      script: add-ceilometer-service.sh {{openrc_file_location}}
      tags: services
