---
- hosts: all
  name: Install neutron

  vars_files:
    - environment.yaml
    - paths.yaml

  vars:

    project: neutron

    ml2_plugins:
      ml2:
        plugins/ml2/ml2_conf.ini
      linuxbridge:
        plugins/ml2/linuxbridge_agent.ini

  roles:
    - clone
    - install
    - { role: config, project: neutron,
        config_files: [neutron.conf, dhcp_agent.ini, metadata_agent.ini],
        tags: config }
    - { role: mysql, project: neutron, manage_command: neutron-db-manage,
        sync_command: "upgrade head", tags: database }
    - { role: service, project: neutron, port: 9696, type: network,
        description: "OpenStack Networking", tags: service }
