---
- hosts: all
  vars:
    - repo_dir: /home/femnad/z/gl/openstack/nova
    - openrc_file_location: /home/femnad/y/admin-openrc.sh
    - db_user: root
    - db_password: naber
    - compute_driver: libvirt.LibvirtDriver
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - libmysqlclient-dev
        - libpq-dev
        - python-libvirt
  tasks:
    - git: repo=git://git.openstack.org/openstack/nova dest={{repo_dir}} version=stable/kilo accept_hostkey=yes
    - script: install-nova.sh {{repo_dir}}
      become: yes
    - mysql_db: name=nova state=present login_user={{db_user}} login_password={{db_password}}
      tags: init_db
    - mysql_user: name=nova password=nova priv=*.*:ALL state=present login_user={{db_user}} login_password={{db_password}}
      tags: init_db
    - command: nova-manage db sync
      become: yes
      tags: init_db
    - script: configure-nova.sh {{compute_driver}}
      become: yes
    - script: add-nova-service.sh {{openrc_file_location}}
