---
- hosts: all
  name: Install neutron

  vars_files:
    - environment.yaml
    - paths.yaml

  vars:

    project: neutron

    pip_deps:
      python-memcached:
        1.58

    config:
      config_files: [neutron.conf, dhcp_agent.ini, l3_agent.ini,
                     metadata_agent.ini]

    ml2_plugins:
      ml2:
        plugins/ml2/ml2_conf.ini
      linuxbridge:
        plugins/ml2/linuxbridge_agent.ini

    db:
      manage_command:
        neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini
      sync_command:
        upgrade head

    service:
      description:
        OpenStack Networking
      port:
        9696
      type:
        network

  vars_prompt:

    - name: physical_network_interface
      prompt: Physical network interface?
      default: eth1

  roles:
    - pip
    - clone
    - install
    - config
    - mysql
    - service
    - rabbitmq
