---
- hosts: all
  name: Install neutron

  vars_files:
    - environment.yaml
    - paths.yaml

  vars:

    project: neutron

    config:
      config_files: [neutron.conf, dhcp_agent.ini, metadata_agent.ini]

    ml2_plugins:
      ml2:
        plugins/ml2/ml2_conf.ini
      linuxbridge:
        plugins/ml2/linuxbridge_agent.ini

    db:
      manage_command:
        neutron-db-manage
      sync_command:
        upgrade head

    service:
      description:
        OpenStack Networking
      port:
        9696
      type:
        network

  roles:
    - clone
    - install
    - config
    - mysql
    - service
    - rabbitmq
