---
- hosts: all
  name: Install Glance

  vars_files:
    - environment.yaml
    - paths.yaml

  vars:

    project:
      glance

    config:
      config_files: [glance-api.conf, glance-registry.conf]
      api_paste_files: [glance-api-paste.ini, glance-registry-paste.ini]

    service:
      description:
        OpenStack Image Service
      port:
        9292
      type:
        image

  roles:
    - clone
    - install
    - config
    - mysql
    - service
