---
- hosts: all
  vars_files:
    - environment.yaml
    - paths.yaml
  roles:
    - { role: clone, project: glance }
    - { role: install, project: glance }
    - { role: config, project: glance, config_files: [glance-api, glance-registry] }
    - { role: mysql, project: glance }
    - { role: service, project: glance, port: 9292,
        description: "OpenStack Image Service", type: image }
