---
- hosts: all
  vars:
    - keystone_pip_packages:
        python-openstackclient:
          "{{openstackclient_version}}"
        pymysql:
          "{{pymysql_version}}"
        python-memcached:
          "{{python_memcached_version}}"
        pytz:
          "{{pytz_version}}"
  vars_files:
    - environment.yaml
    - paths.yaml
  roles:
    - { role: package, project: keystone, packages: [git, mariadb-server, memcached,
        libffi-dev, libssl-dev, libmariadbclient-dev, python-dev, python-virtualenv,
        rabbitmq-server], pip_packages: "{{keystone_pip_packages}}", tags: [reqs] }
    - { role: clone, project: keystone, tags: clone }
    - { role: install, project: keystone, tags: [install] }
    - { role: config, project: keystone, config_files: [keystone],
        sample_config_dir: "{{base_clone_path}}/keystone/etc",
        api_paste_files: [keystone-paste.ini], tags: [config] }
    - { role: mysql, project: keystone, tags: [database] }
    - { role: bootstrap, tags: [service] }
  tasks:
    - name: Add keystone Unix user group
      group: name=keystone state=present
      become: yes
      tags: fernet-setup
    - name: Add keystone Unix user
      user: name=keystone group=keystone
      become: yes
      tags: fernet-setup
    - name: Initialize Fernet key repository
      file: path=/etc/keystone/fernet-keys owner=keystone group=keystone mode=0700
      become: yes
      tags: fernet-setup
    - name: Initialize Fernet tokens
      command: "{{virtualenv_bin}}/keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone"
      become: yes
      tags: fernet-setup
