---
- hosts: all
  vars:
    db_user: root
    db_password: naber
    keystone_repo_dir: /home/femnad/z/gl/openstack/keystone
    os_token: naber
  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - mariadb-server
        - crudini
        - python-dev
        - python-setuptools
        - rabbitmq-server
      when: ansible_os_family == "Debian"
  tasks:
    - script: add-db-admin.sh
    - script: set-hosts.sh controller
      become: yes
    - git: repo=git://git.openstack.org/openstack/keystone dest={{keystone_repo_dir}} version=stable/kilo accept_hostkey=yes
    - script: install-keystone.sh {{keystone_repo_dir}}
      become: yes
    - mysql_db: name=keystone state=present login_user={{db_user}} login_password={{db_password}}
    - mysql_user: name=keystone password=keystone priv=*.*:ALL state=present login_user={{db_user}} login_password={{db_password}}
    - script: bootstrap-keystone.sh {{keystone_repo_dir}}
      become: yes
    - script: configure-keystone.sh
      become: yes
    - script: add-keystone-services.sh {{os_token}}
