---
- hosts: all
  name: Install Glance

  vars_files:
    - environment.yaml
    - paths.yaml

  vars:

    project:
      glance

    config:
      config_files: [glance-api.conf, glance-registry.conf]
      api_paste_files: [glance-api-paste.ini, glance-registry-paste.ini]

    endpoint:
      http://{{ controller_host }}:9292

    pip_deps:
      python-memcached:
        1.58

    service:
      name:
        glance
      description:
        OpenStack Image Service
      type:
        image
      endpoints:
        - interface:
            public
          url:
            "{{ endpoint }}"
        - interface:
            internal
          url:
            "{{ endpoint }}"
        - interface:
            admin
          url:
            "{{ endpoint }}"

    systemd_services:
      - name:
          glance-registry
        description:
          Glance Registry Service
        exec:
          "{{ virtualenv_bin }}/glance-registry"
        user_service:
          no
      - name:
          glance-api
        description:
          Glance API Service
        exec:
          "{{ virtualenv_bin }}/glance-api"
        user_service:
          no

  roles:
    - pip_clone_install
    - pip_packages
    - config
    - mysql
    - component
    - systemd_services
