---
- name: Install Keystone
  hosts: all

  vars_files:
    - environment.yaml
    - paths.yaml

  vars:

    project:
      keystone

    config:
      config_files: keystone.conf
      api_paste_files: keystone-paste.ini

    pip_deps:
      Babel:
        2.3.4
      python-openstackclient:
        3.11.0

  roles:
    - pip_clone_install
    - pip_packages
    - config
    - mysql
    - fernet
    - apache
    - bootstrap
    - envrc
