---
- hosts: all
  vars_files:
    - environment.yaml
    - paths.yaml
  roles:
    - { role: repo-clone-install, project: glance }
    - { role: config, project: glance }
    - { role: mysql, project: glance }
    - { role: deprecated-service, project: glance, port: 9292,
    description: "OpenStack Image Service", type: image }
