---
- vars_files:
    - path_vars.yaml
  hosts: all
  vars:
    keystone_repo_dir: "{{base_clone_path}}/keystone"
    os_token: nekot
    admin_password: nimda
  pre_tasks:
    - name: Install requirements with apt
      apt: name={{item}} state=latest
      become: yes
      with_items:
        - crudini
        - git
        - mariadb-server
        - memcached
        - libffi-dev
        - libssl-dev
        - libmariadbclient-dev
        - python-dev
        - python-virtualenv
        - rabbitmq-server
      when: ansible_os_family == "Debian"
      tags: reqs
  tasks:
    - name: Add database admin
      script: add-db-admin.sh {{db_user}} {{db_password}}
      tags: db-admin-init
      become: yes
    - name: set hostname
      script: set-hosts.sh controller
      become: yes
      tags: host-init
    - name: Clone keystone repo
      git: repo=git://git.openstack.org/openstack/keystone dest={{keystone_repo_dir}} version=stable/kilo accept_hostkey=yes
      tags: clone
    - name: Install keystone
      script: install-keystone.sh {{keystone_repo_dir}} {{virtualenv_path}}
      tags: install
    - name: Install required Python packages
      pip: name={{item}} virtualenv={{virtualenv_path}}
      with_items:
        - MySQL-python virtualenv
        - python-memcached
      tags: install-pip
    - name: Add keystone database
      mysql_db: name=keystone state=present login_user={{db_user}} login_password={{db_password}}
      tags: db-init
    - name: Add keystone database user
      mysql_user: name=keystone password=keystone priv=*.*:ALL state=present login_user={{db_user}} login_password={{db_password}}
      tags: db-init
    - name: Generate configuration
      script: bootstrap-keystone.sh {{keystone_repo_dir}}
      become: yes
      tags: genconfig
    - name: Configure keystone
      script: configure-keystone.sh {{os_token}}
      become: yes
      tags: config
    - name: Sync keystone database
      command: "{{virtualenv_path}}/bin/python {{virtualenv_path}}/bin/keystone-manage db_sync"
      become: yes
      tags: sync-db
    - name: Add keystone services
      script: add-keystone-services.sh {{os_token}} {{virtualenv_path}} {{admin_password}}
      tags: service
    - name: Add admin openrc file
      script: add-admin-openrc-file.sh {{openrc_dir}} {{admin_openrc_file}} {{admin_password}}
      tags: openrc
