---
- hosts: all
  vars:

  pre_tasks:
    - apt: name={{item}} state=latest
      become: yes
      with_items:
        - mariadb-server
        - crudini
        - python-mysqldb
  tasks:
    - git: repo=git://git.openstack.org/openstack/keystone dest=~/z/gl/openstack/keystone version=juno-eol accept_hostkey=yes
    - script: install-keystone.sh
    - mysql_db: name=keystone state=present login_user=boot login_password=borek
    - mysql_user: name=keystone password=keystone priv=*.*:ALL state=present login_user=boot login_password=borek
    - script: bootstrap-keystone.sh
