---
- hosts: all
  vars_files:
    - environment.yaml
    - paths.yaml
  roles:
    - { role: clone, project: heat }
    - { role: install, project: heat, tags: install }
    - { role: config, project: heat, config_files: [heat], tags: config }
    - { role: mysql, project: heat, tags: database }
    - { role: deprecated-service, project: heat, description: Orchestration, port: 8004,
        endpoint: "/v1/%\\(tenant_id\\)s", type: orchestration, tags: service }
