---
- hosts: all
  name: Install Glance

  vars_files:
    - environment.yaml
    - paths.yaml

  vars:

    project:
      glance

    config:
      config_files: [glance-api.conf, glance-registry.conf]
      api_paste_files: [glance-api-paste.ini, glance-registry-paste.ini]

    endpoint:
      http://{{ controller_host }}:9292

    service:
      name:
        glance
      description:
        OpenStack Image Service
      type:
        image
      endpoints:
        - interface:
            public
          url:
            "{{ endpoint }}"
        - interface:
            internal
          url:
            "{{ endpoint }}"
        - interface:
            admin
          url:
            "{{ endpoint }}"

  roles:
    - pip_clone_install
    - config
    - mysql
    - component
