---
- hosts: all
  vars_files:
    - environment.yaml
    - paths.yaml
  roles:
    - { role: clone, project: glance }
    - { role: install, project: glance }
    - { role: config, project: glance, config_files: [glance-api.conf, glance-registry.conf],
        api_paste_files: [glance-api-paste.ini, glance-registry-paste.ini],
        tags: config}
    - { role: mysql, project: glance, tags: database }
    - { role: service, project: glance, port: 9292,
        description: "OpenStack Image Service", type: image, tags: service }
