---
- hosts: all
  vars_files:
    - path_vars.yaml
    - credential-params.yaml
  vars:
    - repo_dir: "{{base_clone_path}}/neutron"
  pre_tasks:
    - name: Install requirements with apt
      apt: name={{item}} state=installed
      with_items:
        - openvswitch-switch
      tags: reqs
      become: yes
    - name: Create database
      mysql_db: name=neutron state=present login_user={{db_user}} login_password={{db_password}}
      tags: db-init
    - name: Create database user
      mysql_user: name=neutron password=neutron priv=*.*:ALL state=present login_user={{db_user}} login_password={{db_password}}
      tags: db-init
  tasks:
    - name: Clone neutron repository
      git: repo=git://git.openstack.org/openstack/neutron dest={{repo_dir}} version=stable/kilo accept_hostkey=yes
      tags: clone
    - name: Install Neutron
      script: install-neutron.sh {{repo_dir}} {{virtualenv_activator}}
      tags: install
    - name: Generate Neutron configuration
      script: copy-neutron-config.sh {{repo_dir}}
      become: yes
      tags: genconfig
    - name: Configure Neutron
      script: configure-neutron-network-node.sh {{local_ip}}
      become: yes
      tags: config
    - name: Synchronize database
      command: "{{virtualenv_python}} {{virtualenv_bin}}/neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head"
      tags: db-sync
    - name: Add neutron services
      script: add-neutron-service.sh {{admin_openrc_file}} {{virtualenv_activator}}
      tags: service
    - name: Create neutron log directory
      file: name=/var/log/neutron state=directory
    - name: Edit sysctl file
      script: edit-sysctl.sh
      become: yes
      tags: sysctl
