---
- hosts: all
  vars:
    - nova_pip_packages:
        libvirt-python:
          "{{libvirt_version}}"
        python-memcached:
          "{{python_memcached_version}}"
        pymysql:
          "{{pymysql_version}}"
  vars_files:
    - environment.yaml
    - paths.yaml
  roles:
    - { role: package,  project: nova,
        packages: [libffi-dev, libmysqlclient-dev, libpq-dev, libvirt-bin, libvirt-dev, libxml2-dev,
                 libxslt1-dev, nbd-client, pkg-config, python-dev, python-mysqldb, qemu-kvm],
        pip_packages: "{{nova_pip_packages}}", tags: reqs }
    - { role: clone, project: nova, tags: clone }
    - { role: install, project: nova, tags: install }
    - { role: config, project: nova, config_files: [nova], tags: config }
    - { role: mysql, project: nova, sync_command: "db sync", tags: database }
    - { role: mysql, project: nova_api, sync_command: "api_db sync",
        manage_command: "nova-manage", tags: [database,database-nova-api] }
    - { role: service, project: nova, port: 8774, endpoint: "/v2.1/%\\(tenant_id\\)s",
        type: compute, description: "OpenStack Compute", tags: service }
