---
- hosts: all
  vars_files:
    - environment.yaml
    - paths.yaml
  vars:
    repo_dir: "{{base_clone_path}}/python-openstackclient"
  tasks:
    - name: Clone openstackclient repository
      git: repo=git://git.openstack.org/openstack/python-openstackclient dest={{repo_dir}}
           version={{openstackclient_version}} accept_hostkey=yes
      tags: clone
    - name: Install openstackclient
      script: install-component.sh {{repo_dir}} {{virtualenv_path}}
      tags: install
