---
- hosts: all
  name: Install Nova

  vars_files:
    - environment.yaml
    - paths.yaml

  vars:

    project:
      nova

    deps:
      apt:
        [libpq-dev, libvirt-bin, libvirt-dev, libxml2-dev, libxslt1-dev,
         nbd-client, pkg-config, qemu-kvm]

    pip_deps:
      libvirt-python:
        1.3.1

    config:
      config_files: [nova.conf]
      config_prefix: etc/nova

    service:
      description:
        OpenStack Compute
      endpoint:
        v2.1/%\(tenant_id\)s
      port:
        8774
      type: compute

    nova_db:
      sync_command:
        db sync

    nova_api_db:
      name:
        nova_api
      sync_command:
        api_db sync


  roles:
    - packages
    - pip
    - clone
    - install
    - config
    - { role: mysql, db: "{{ nova_db }}" }
    - { role: mysql, db: "{{ nova_api_db }}" }
    - service
