---
- name:
    Initialize log path
  file:
    path:
      "{{ log_dir }}/{{ _self.base_name }}"
    state:
      directory
    owner:
      "{{ _self.owner | default(omit) }}"
  when:
    "{{ _self.base_name | default(false) }}"
  tags:
    init-paths

- name:
    Initialize custom paths
  file:
    path:
      "{{ _self.custom }}"
    state:
      directory
  when:
    _self.custom | default(false)
  tags:
    init-paths
