---
- name:
    Initialize log path
  file:
    path:
      "{{ log_dir }}/{{ _self.base_name }}"
    state:
      directory
    owner:
      "{{ _self.owner | default(omit) }}"
    group:
      "{{ _self.group | default(omit) }}"
  become:
    "{{ (_self.owner is defined) or (_self.group is defined) }}"
  when:
    _self.base_name | default(false)
  tags:
    init-paths

- name:
    Initialize custom paths
  file:
    path:
      "{{ _self.custom }}"
    state:
      directory
  when:
    _self.custom | default(false)
  tags:
    init-paths
