---
- name:
    Initialize log path
  file:
    path:
      "{{ log_dir }}/{{ project }}"
    state:
      directory
  tags:
    init-paths

- name:
    Initialize custom paths
  file:
    path:
      "{{ _self.custom }}"
    state:
      directory
  when:
    _self.custom | default(false)
  tags:
    init-paths
