---
- name: Create RabbitMQ user
  rabbitmq_user: user={{ rabbitmq_user }} password={{ rabbitmq_password }}
                 vhost=/ configure_priv=.* read_priv=.* write_priv=.*
                 state=present
  become: yes
  tags: amqp
