---
_default_config:
  config_files:
    ["{{ project }}.conf"]
  config_prefix:
    "etc"
  api_paste_files:
    [api-paste.ini]
  generate_policy:
    false
  policy_files:
    [policy.json]

_config:
  "{{ _default_config | combine(config) }}"

sample_config_dir:
  "{{ repo_clone_path }}/{{ project }}/{{ _config.config_prefix }}"

paths:
  base_name:
    "{{ project }}"
