---
dependencies:
  - { role: packages, deps: "{{ _dependencies }}",
      tags: db }
  - { role: hosts, tags: db }
  - { role: mysql_admin, tags: db }
  - { role: pip_packages,
      pip_deps: "{{ _pip_deps }}",
      tags: db }
