---
- name: Set character set to utf8
  replace: dest=/etc/mysql/mariadb.conf.d/{{ item }} regexp=utf8mb4 replace=utf8
  with_items:
    - 50-mysql-clients.cnf
    - 50-server.cnf
    - 50-client.cnf
  become: yes
  tags: db, db-charset
  notify: restart mysql


- name: Drop {{project}} database
  mysql_db: name={{version_release}}_{{project}} state=absent
            login_host={{db_host}}
            login_user={{db_user}} login_password={{db_password}}
  tags: db, db-purge

- name: Add {{project}} database
  mysql_db: name={{version_release}}_{{project}} state=present
            login_host={{db_host}}
            login_user={{db_user}} login_password={{db_password}}
  tags: db, db-init

- name: Add {{project}} database user
  mysql_user: name={{project}} password={{project}} priv=*.*:ALL
              state=present login_host={{db_host}}
              login_user={{db_user}} login_password={{db_password}}
  tags: db, db-init

- name: Synchronize {{project}} database
  command: "{{virtualenv_bin}}/{{manage_command}} {{sync_command}}"
  become: yes
  tags: db, db-sync
