---
- name: Set character set to utf8
  replace: dest=/etc/mysql/mariadb.conf.d/{{ item }} regexp=utf8mb4 replace=utf8
  with_items:
    - 50-mysql-clients.cnf
    - 50-server.cnf
    - 50-client.cnf
  become: yes
  when:
    ansible_distribution == "Ubuntu" and ansible_distribution_version | version_compare('16.04', '>=')
  notify: restart mysql
  tags: db, db-charset

- name: Drop {{ _db.name }} database
  mysql_db: name={{version_release}}_{{ _db.name }} state=absent
            login_host={{db_host}}
            login_user={{db_user}} login_password={{db_password}}
  tags: db, db-purge

- name: Add {{ _db.name }} database
  mysql_db: name={{version_release}}_{{ _db.name }} state=present
            login_host={{db_host}}
            login_user={{db_user}} login_password={{db_password}}
  tags: db, db-init

- name: Add {{ _db.name }} database user
  mysql_user: name={{ project }} password={{project}} priv=*.*:ALL
              state=present host=controller login_host={{db_host}}
              login_user={{db_user}} login_password={{db_password}}
  tags: db, db-init

- name: Synchronize {{project}} database
  command: "{{virtualenv_bin}}/{{ _db.manage_command }} {{ _db.sync_command }}"
  become: yes
  tags: db, db-sync
