---
- name: Purge old {{project}} configuration files
  file: path=/etc/{{project}} state=absent
  become: yes
  tags: config-purge
- name: Create config directory
  file: path=/etc/{{project}} state=directory
  tags: config-init
  become: yes
- name: Configure {{project}}
  template: src="{{item}}-config-template.j2" dest=/etc/{{project}}/{{item}}.conf
  tags: config-save
  with_items: "{{config_files}}"
  become: yes
- name: Copy {{project}} API configs
  command: "cp {{sample_config_dir}}/{{item}} /etc/{{project}}/{{item}}"
  become: yes
  tags: config-api
  with_items:
    "{{api_paste_files}}"
- name: Copy {{project}} policy configs
  command: "cp {{sample_config_dir}}/{{item}} /etc/{{project}}/{{item}}"
  become: yes
  tags: config-policy
  with_items:
    "{{policy_files}}"
- name: Copy additional configuration files for {{project}}
  command: "cp {{sample_config_dir}}/{{item}} /etc/{{project}}/{{item}}"
  with_items:
    "{{extra_config | default([])}}"
  become: yes
  tags: config-extra
