---
- name: Purge old {{project}} configuration files
  file: path=/etc/{{project}} state=absent
  become: yes
  tags: config-purge

- name: Create config directory
  file: path=/etc/{{project}} state=directory
  tags: config, config-init
  become: yes

- name: Configure {{project}}
  template: src="{{item}}.j2" dest=/etc/{{project}}/{{item}}
  tags: config, config-save
  with_items: "{{config_files}}"
  become: yes

- name: Create ml plugins config directory
  file: path=/etc/neutron/plugins/ml2 state=directory
  tags: config, config-ml2
  when: project == "neutron"
  become: yes

- name: Configure {{project}}
  template: src="{{project}}-{{item.key}}-config-template.j2" dest=/etc/{{project}}/{{item.value}}
  with_dict: "{{ml2_plugins | default({})}}"
  become: yes
  when: project == "neutron"
  tags: config, config-ml2

- name: Copy {{project}} API configs
  command: "cp {{sample_config_dir}}/{{item}} /etc/{{project}}/{{item}}"
  become: yes
  tags: config, config-api
  with_items:
    "{{api_paste_files}}"

- name: Copy {{project}} policy configs
  command: "cp {{sample_config_dir}}/{{item}} /etc/{{project}}/{{item}}"
  become: yes
  tags: config, config-policy
  with_items:
    "{{policy_files}}"

- name: Copy additional configuration files for {{project}}
  command: "cp {{sample_config_dir}}/{{item}} /etc/{{project}}/{{item}}"
  with_items:
    "{{extra_config | default([])}}"
  become: yes
  tags: config, config-extra

- name: Initialize log directory
  file: path=/var/log/{{ project }} state=directory
  become: yes
  tags: config, config-log-dir
