---
- name: Generate {{project}} configuration template
  command: tox -egenconfig chdir={{base_clone_path}}/{{project}}
  tags: genconfig
  when: not (project == "keystone")
- name: Purge old {{project}} configuration files
  file: path=/etc/{{project}} state=absent
  become: yes
  tags: config-purge
- name: Create config directory
  file: path=/etc/{{project}} state=directory
  tags: config-init
  become: yes
- name: Configure {{project}}
  template: src="{{item}}-config-template.j2" dest=/etc/{{project}}/{{item}}.conf
  tags: config-save
  with_items: "{{config_files}}"
  become: yes
- name: Copy {{project}} API and policy configs
  command: "cp {{sample_config_dir}}/{{item}} /etc/{{project}}/{{item}}"
  tags: config-rest
  with_items:
    - "{{api_paste_file}}"
    - "{{policy_file}}"
  become: yes
