---
- name: Create {{project}} user
  environment: "{{admin_environment}}"
  command: "{{deprecated_keystoneclient}} user-create --name {{project}} --pass {{project}}"
  tags: service-user
- name: Add admin role to {{project}} user
  environment: "{{admin_environment}}"
  command: "{{deprecated_keystoneclient}} user-role-add --user {{project}} --tenant service --role admin"
  tags: service-admin-role
- name: Create service for {{project}}
  environment: "{{admin_environment}}"
  command: "{{deprecated_keystoneclient}} service-create --name {{project}} \
            --description '{{description}}' --type {{type}}"
  tags: service-create
- name: Create endpoints for {{project}}
  environment: "{{admin_environment}}"
  shell: "{{deprecated_keystoneclient}} endpoint-create \
  --service-id $({{deprecated_keystoneclient}} service-list | awk '/ image / {print $2}') \
  --publicurl http://controller:{{port}} \
  --internalurl http://controller:{{port}} \
  --adminurl http://controller:{{port}} \
  --region {{region}}"
  tags: service-endpoint
