---
- name: Upgrade pip
  pip: name=pip state=latest virtualenv={{virtualenv_path}}
  tags: pip-upgrade
- name: Install common pip packages
  pip: name={{item.key}} version={{item.value}} virtualenv={{virtualenv_path}}
  with_dict: "{{common_pip_packages}}"
  tags: pip-common
