---
- name: Install python virtualenv
  apt: name=python-virtualenv state=latest
  become: yes
  tags: python-virtualenv
- name: Create the virtual environment
  command: virtualenv {{virtualenv_path}}
  args:
    creates: "{{virtualenv_python}}"
  tags: python-virtualenv
- name: Upgrade pip
  pip: name=pip state=latest virtualenv={{virtualenv_path}}
  tags: pip-upgrade
- name: Install common pip packages
  pip: name={{item.key}} version={{item.value}} virtualenv={{virtualenv_path}}
  with_dict: "{{common_pip_packages}}"
  tags: pip-common
- name: Install common packages with apt
  apt: name={{item}} state=latest
  with_items:
    - git
    - libffi-dev
    - libmariadbclient-dev
    - libssl-dev
    - mariadb-server
    - memcached
    - python-dev
    - rabbitmq-server
  when: ansible_os_family == "Debian"
  become: yes
  tags: apt-common
