- name: Add keystone Unix user group
  group: name=keystone state=present
  become: yes
  tags: fernet, fernet-unix-user

- name: Add keystone Unix user
  user:
    name:
      keystone
    group:
      keystone
  become: yes
  tags: fernet, fernet-unix-group

- name: Initialize Fernet key repository
  file: path={{ keystone_paths.fernet_keys }} state=directory owner=keystone group=keystone mode=0700
  tags: fernet, fernet-key-dir
  become:
    yes

- name: Initialize Fernet key repositories
  command:
    "{{ virtualenv_bin }}/keystone-manage {{ item }} --keystone-user keystone --keystone-group keystone"
  with_items:
    - fernet_setup
    - credential_setup
  become:
    yes
  tags: fernet, fernet-key-setup
