---
- name:
    Check for {{ os_service }} service
  environment:
    "{{ os_environment }}"
  command:
    "{{ admin_bin }}/openstack service show {{ os_service }}"
  register:
    service_check
  failed_when:
    not service_check.rc in [0, 1]
  tags:
    service

- name:
    Create service {{ os_service }}
  environment:
    "{{ os_environment }}"
  command:
    "{{ admin_virtualenv }}/bin/openstack service create --name {{ os_service }} --description '{{ description }}' {{ os_type }}"
  when:
    service_check.rc == 1
  tags:
    service
