---
- name: Create {{project}} user
  environment: "{{admin_environment}}"
  command: "{{openstackclient_bin}} user create --domain default {{project}} --password {{project}}"
  tags: service-user
- name: Add admin role to {{project}} user
  environment: "{{admin_environment}}"
  command: "{{openstackclient_bin}} role add --project service --user {{project}} admin"
  tags: service-admin-role
- name: Create service for {{project}}
  environment: "{{admin_environment}}"
  command: "{{openstackclient_bin}} service create --name {{project}} \
            --description '{{description}}' {{type}}"
  tags: service-create
- name: Create public endpoint for {{project}}
  environment: "{{admin_environment}}"
  command: "{{openstackclient_bin}} endpoint create --region {{region}} {{type}} \
               public http://{{controller_host}}:{{port}}/{{endpoint}}"
  tags: service-endpoint-public
- name: Create internal endpoint for {{project}}
  environment: "{{admin_environment}}"
  command: "{{openstackclient_bin}} endpoint create --region {{region}} {{type}} \
               internal http://{{controller_host}}:{{port}}/{{endpoint}}"
  tags: service-endpoint-internal
- name: Create admin endpoint for {{project}}
  environment: "{{admin_environment}}"
  command: "{{openstackclient_bin}} endpoint create --region {{region}} {{type}} \
               admin http://{{controller_host}}:{{port}}/{{endpoint}}"
  tags: service-endpoint-admin
- name: Create the heat stack user role
  command: "{{openstackclient_bin}} role create heat_stack_user"
  environment: "{{admin_environment}}"
  when: project == "heat"
  tags: heat-stack-user
- name: Create heat domain
  command: "{{virtualenv_bin}}/heat-keystone-setup-domain \
            --stack-user-domain-name heat_user_domain \
            --stack-domain-admin heat_domain_admin \
            --stack-domain-admin-password heat"
  environment: "{{admin_environment}}"
  when: project == "heat"
  tags: heat-domain
